title: AquaINFRA Training Handbooks
description: A collection of training handbooks and use case documentation for the AquaINFRA project.

# Branding
# logo: "assets/images/logo_white.svg"  <-- Removed, used in header.html
baseurl: "/AquaINFRA_Training_Handbooks"
url: "https://mehrad1994.github.io"

# Features
mermaid:
  enabled: true
search_enabled: false # Search not implemented in lite template yet

# Footer & Citations
gh_url: https://github.com/Mehrad1994/AquaINFRA_Training_Handbooks
# footer_content handled in _includes/footer.html
